spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: microservice
      authentication-database: microservice

server:
  servlet:
    context-path: /uaa
  port: 8081